### ISSUE TITLE
Example Request: Okta/A2 SAML Setup Example

### ISSUE THREAD

**Issue by danielcbright** [chef-cft/chef-examples#1]
## Example Request

This example request includes usage of the following Chef products:

   - [x] Chef Automate 
     * Includes Chef Server, Client, Backend, ChefDK and Supermarket
   - [ ] Chef Workstation
     * Includes Chef Workstation only
   - [ ] Habitat
     * Includes Habitat, Habitat Builder (on-prem and SaaS)
   - [ ] InSpec
     * Includes InSpec, Ad-hoc Automate jobs, Audit Cookbook

## Problem Statement

A HowTo guide is needed to show how to setup Automate 2.0 with Okta SAML/SSO authentication. 

### External References

* Automate SAML Docs: https://automate.chef.io/docs/configuration/#saml
* Setting up a SAML Application in Okta: https://developer.okta.com/standards/SAML/setting_up_a_saml_application_in_okta

### Additional Notes

N/A

**Comment by bnwoods** [comment]
I got you fam

**Comment by danielcbright** [comment]
Closed with PR #2
