### ISSUE TITLE
Example Request: How Should I Organize Policyfiles in SCM?

### ISSUE THREAD

**Issue by danielcbright** [chef-cft/chef-examples#18]
## Example Request

This example request includes usage of the following Chef products:

   - [x] Chef Automate 
     * Includes Chef Server, Client, Backend, ChefDK and Supermarket
   - [ ] Chef Workstation
     * Includes Chef Workstation only
   - [ ] Habitat
     * Includes Habitat, Habitat Builder (on-prem and SaaS)
   - [ ] InSpec
     * Includes InSpec, Ad-hoc Automate jobs, Audit Cookbook

## Problem Statement

Policyfiles are the Chef recommended way of packaging and converging cookbooks onto a node. Currently, there's a lot of opinion out there on how to _use_ policyfiles, but not much on how to _organize_ them. Due to this, it's hard to decide how to organize Policyfiles in SCM when accounting for multiple teams, org silos, and future scaling. 

### External References

* https://blog.chef.io/policyfiles-a-chef-best-practice/

### Additional Notes

This example should show the following:

* It should take into account a basic "app stack" that a typical Chef customer would have in their own environment.
* It should break down the individual components of Policyfiles are created and deployed, and show where SCM is used for each one.
* It needs to be opinionated, and give newcomers to Policyfiles a good foundation on which to start building out their code base, yet also be flexible enough to be modified in the future.
* It should build on consensus of Chef professionals, and not be the opinion of just one person.

**Comment by scottvidmar** [comment]
Hi Dan, 

I just saw this, and have something going that has this angle laid out. It spawned from a discussion with Chef eng and a couple of others that happened last year. May be worth opening the discussion, and I can open a PR to give us a starting point.

https://docs.google.com/document/d/1afcfG1Eln-ogRFVPMRCrJdJPYiNNV707CQVTAlDxhP0/edit?usp=sharing
